import type { Metadata } from "next";
import "@app/ui/styles.css";
import { Inter } from "next/font/google";
import { TRPCProvider } from "@/trpc/client";

const font = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${font.variable} min-h-screen bg-background font-sans antialiased`}
			>
				<TRPCProvider>{children}</TRPCProvider>
			</body>
		</html>
	);
}
